config/routes.rb
CheerMeOn::Application.routes.draw do
  resources :users, :goals
  resource :session, only: [:new, :create, :destroy]

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username
  validates :session_token, :username, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return user if !user.nil? && user.is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end


  private

  attr_reader :password

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :require_current_user!, except: [:index]

  def index
    @goals = Goal.where("private = true")
    render :index
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(params[:goal])

    if @goal.save
      redirect_to goals_url
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update_attributes(params[:goal])
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])

    unless @user.nil?
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end

  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, except: [:new, :create]

  def new
    @user = User.new()
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end


  end

  def show
    @user = User.find(params[:id])
    render :show

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:token])
  end

  def logged_in?
    !current_user.nil?
  end

  def require_current_user!
    redirect_to new_session_url unless logged_in?
  end

  def login(user)
    session[:token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:token] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>Goals</h1>

<ul>
  <% @goals.each do |goal| %>
    <li>
      <%= goal.title %>
    </li>
  <% end %>
</ul>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="goal_title">Title:</label>
  <input type="text" name="goal[title]" value="@goal.title" id="goal_title">
  <br>
  <input type="radio" name="goal[:private]" id="goal_private_false" value="false">
  <label for="goal_private_false">Public</label>
  <input type="radio" name="goal[:private]" id="goal_private_true" value="true">
  <label for="goal_private_true">Private</label>


  <p><input type="submit" value="Create Goal"></p>
</form>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

Status: <%= (@goal.private) ? "Private" : "Public" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheerMeOn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if logged_in? %>
  Hello <%= current_user.username%>
  <%= button_to "Log Out", session_url, method: :delete %>
  <% else %>
  <%= link_to "Sign In", new_session_url, method: :get %>
  <%= link_to "Sign Up", new_user_url, method: :get %>

  <% end %>


  <% if !flash[:errors].nil? %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST" accept-charset="utf-8">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>" id="authenticity_token">

	<label for="user_username">Username:</label>
	<input type="text" name="user[username]" value="<%= @user.username %>" id="user_username">
	<br>
	<label for="user_password">Password:</label>
	<input type="password" name="user[password]" id="user_password">

	<p><input type="submit" value="Create User"></p>
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>